//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubSonic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubSonicErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubSonicErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubSonic.SubSonicErrorMessages", typeof(SubSonicErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbExpression must be of {0}..
        /// </summary>
        internal static string DbExpressionMustBeOfType {
            get {
                return ResourceManager.GetString("DbExpressionMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly qualified name is missing..
        /// </summary>
        internal static string DbProviderFactoryNoAssemblyQualifiedName {
            get {
                return ResourceManager.GetString("DbProviderFactoryNoAssemblyQualifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not declare a declared public static Instance field..
        /// </summary>
        internal static string DbProviderFactoryNoInstance {
            get {
                return ResourceManager.GetString("DbProviderFactoryNoInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not inherit from {1}..
        /// </summary>
        internal static string DbProviderFactorySubClassError {
            get {
                return ResourceManager.GetString("DbProviderFactorySubClassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0}is not registed with the db model..
        /// </summary>
        internal static string EntityTypeIsNotRegisteredException {
            get {
                return ResourceManager.GetString("EntityTypeIsNotRegisteredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected expression of type DbTableExpression..
        /// </summary>
        internal static string ExpectedDbTableExpression {
            get {
                return ResourceManager.GetString("ExpectedDbTableExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Method {0} is not supported..
        /// </summary>
        internal static string ExpressionNotSupported {
            get {
                return ResourceManager.GetString("ExpressionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not implement the {1} interface..
        /// </summary>
        internal static string MissingInterfaceImplementation {
            get {
                return ResourceManager.GetString("MissingInterfaceImplementation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supply the name of the containing method..
        /// </summary>
        internal static string MissingNameArgumentException {
            get {
                return ResourceManager.GetString("MissingNameArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IServiceCollection is not found in the IOC container..
        /// </summary>
        internal static string MissingServiceCollectionException {
            get {
                return ResourceManager.GetString("MissingServiceCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Available.
        /// </summary>
        internal static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-scalar projections cannot be translated to SQL..
        /// </summary>
        internal static string NonScalarProjection {
            get {
                return ResourceManager.GetString("NonScalarProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not decorated with StoredProcedureAttribute..
        /// </summary>
        internal static string NotDecoratedWithStoredProcedureAttribute {
            get {
                return ResourceManager.GetString("NotDecoratedWithStoredProcedureAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Referenced an unsupported Type&quot;.
        /// </summary>
        internal static string NotSupportedType {
            get {
                return ResourceManager.GetString("NotSupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider &quot;{0}&quot;, is not registered in {1}..
        /// </summary>
        internal static string ProviderInvariantNameNotRegisteredException {
            get {
                return ResourceManager.GetString("ProviderInvariantNameNotRegisteredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select source is not valid type..
        /// </summary>
        internal static string SelectSourceIsNotValid {
            get {
                return ResourceManager.GetString("SelectSourceIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method {0} is a placeholder for a server-side method..
        /// </summary>
        internal static string SqlMethodOnlyForSql {
            get {
                return ResourceManager.GetString("SqlMethodOnlyForSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SqlQueryProvider is null..
        /// </summary>
        internal static string SqlQueryProviderIsNull {
            get {
                return ResourceManager.GetString("SqlQueryProviderIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to undefined column..
        /// </summary>
        internal static string UndefinedReferenceColumn {
            get {
                return ResourceManager.GetString("UndefinedReferenceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown aggregate type: {0}.
        /// </summary>
        internal static string UnknownAggregate {
            get {
                return ResourceManager.GetString("UnknownAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binary operator &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnSupportedBinaryOperator {
            get {
                return ResourceManager.GetString("UnSupportedBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The constant for &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnSupportedConstant {
            get {
                return ResourceManager.GetString("UnSupportedConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The construtor &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnSupportedConstructor {
            get {
                return ResourceManager.GetString("UnSupportedConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member {0} is not supported..
        /// </summary>
        internal static string UnSupportedMemberException {
            get {
                return ResourceManager.GetString("UnSupportedMemberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method {0} is not supported..
        /// </summary>
        internal static string UnSupportedMethodException {
            get {
                return ResourceManager.GetString("UnSupportedMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LINQ expression node of type {0} is not supported..
        /// </summary>
        internal static string UnSupportedNodeException {
            get {
                return ResourceManager.GetString("UnSupportedNodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unary operator &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnSupportedUnaryOperator {
            get {
                return ResourceManager.GetString("UnSupportedUnaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined table types have not data to load from the database..
        /// </summary>
        internal static string UserDefinedTableHaveNoDataToLoad {
            get {
                return ResourceManager.GetString("UserDefinedTableHaveNoDataToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has not been decorated with DbUserDefinedTableTypeAttribute..
        /// </summary>
        internal static string UserDefinedTableNotDefined {
            get {
                return ResourceManager.GetString("UserDefinedTableNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected value to be of type {0}, but found {1}..
        /// </summary>
        internal static string ValueIsNotOfExpectedType {
            get {
                return ResourceManager.GetString("ValueIsNotOfExpectedType", resourceCulture);
            }
        }
    }
}
